-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { businessman_index = 1,  employ_time = 86400,  employ_cash = 12,  rest_time = 3600}
data[2] = { businessman_index = 2,  employ_time = 259200,  employ_cash = 50,  rest_time = 3600}
data[3] = { businessman_index = 3,  employ_time = 432000,  employ_cash = 90,  rest_time = 3600}

return data
