-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[2001] = { reward_index = 2001,  item_name = "钞票",  item_index = 7002,  item_count = 5,  reward_type = 2,  weight = 10,  icon = "rw_tb_2"}
data[2002] = { reward_index = 2002,  item_name = "钞票",  item_index = 7002,  item_count = 6,  reward_type = 2,  weight = 10,  icon = "rw_tb_2"}
data[2003] = { reward_index = 2003,  item_name = "钞票",  item_index = 7002,  item_count = 7,  reward_type = 2,  weight = 10,  icon = "rw_tb_2"}
data[2004] = { reward_index = 2004,  item_name = "钞票",  item_index = 7002,  item_count = 8,  reward_type = 2,  weight = 10,  icon = "rw_tb_2"}
data[2005] = { reward_index = 2005,  item_name = "黄宝石",  item_index = 3001,  item_count = 1,  reward_type = 2,  weight = 8,  icon = "rw_tb_2"}
data[2006] = { reward_index = 2006,  item_name = "蓝宝石",  item_index = 3002,  item_count = 1,  reward_type = 2,  weight = 8,  icon = "rw_tb_2"}
data[2007] = { reward_index = 2007,  item_name = "红宝石",  item_index = 3003,  item_count = 1,  reward_type = 2,  weight = 8,  icon = "rw_tb_2"}
data[2008] = { reward_index = 2008,  item_name = "紫宝石",  item_index = 3004,  item_count = 1,  reward_type = 2,  weight = 8,  icon = "rw_tb_2"}
data[1001] = { reward_index = 1001,  item_name = "金币",  item_index = 7001,  item_count = 100,  reward_type = 1,  weight = 10,  icon = "rw_tb_2"}
data[1002] = { reward_index = 1002,  item_name = "金币",  item_index = 7001,  item_count = 150,  reward_type = 1,  weight = 10,  icon = "rw_tb_2"}
data[1003] = { reward_index = 1003,  item_name = "金币",  item_index = 7001,  item_count = 200,  reward_type = 1,  weight = 10,  icon = "rw_tb_2"}
data[1004] = { reward_index = 1004,  item_name = "金币",  item_index = 7001,  item_count = 250,  reward_type = 1,  weight = 10,  icon = "rw_tb_2"}
data[1005] = { reward_index = 1005,  item_name = "金币",  item_index = 7001,  item_count = 300,  reward_type = 1,  weight = 10,  icon = "rw_tb_2"}
data[1006] = { reward_index = 1006,  item_name = "玻璃",  item_index = 5001,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1007] = { reward_index = 1007,  item_name = "砖块",  item_index = 5002,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1008] = { reward_index = 1008,  item_name = "水泥",  item_index = 5003,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1009] = { reward_index = 1009,  item_name = "锤子",  item_index = 5004,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1010] = { reward_index = 1010,  item_name = "钉子",  item_index = 5005,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1011] = { reward_index = 1011,  item_name = "油漆",  item_index = 5006,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1012] = { reward_index = 1012,  item_name = "铲子",  item_index = 5007,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1013] = { reward_index = 1013,  item_name = "斧头",  item_index = 5008,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}
data[1014] = { reward_index = 1014,  item_name = "锯子",  item_index = 5009,  item_count = 1,  reward_type = 1,  weight = 8,  icon = "rw_tb_2"}

return data
