-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { employ_index = 1001,  employ_name = "简历招聘",  employ_type = 1,  states = {1,2},  states_weight = {7,3},  profession = {1001,1002,1003,1004,1005},  profession_weight = {10,10,10,10,10},  free_interval = 300,  free_times = 3}
data[2001] = { employ_index = 2001,  employ_name = "猎头招聘",  employ_type = 2,  states = {1,2,3,4},  states_weight = {3,4,2,1},  profession = {1001,1002,1003,1004,1005},  profession_weight = {10,10,10,10,10},  free_interval = 82800,  free_times = 1}

return data
