-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[3001] = { employ_index = 3001,  employ_name = "签到奖励",  employ_type = 3,  states = {3},  states_weight = {100},  profession = {1001,1002,1003,1004,1005},  profession_weight = {10,10,10,10,10},  free_interval = 0,  free_times = 0}
data[1001] = { employ_index = 1001,  employ_name = "简历招聘",  employ_type = 1,  states = {1,2},  states_weight = {70,30},  profession = {1001,1002,1003,1004,1005},  profession_weight = {10,10,10,10,10},  free_interval = 300,  free_times = 3}
data[2001] = { employ_index = 2001,  employ_name = "猎头招聘",  employ_type = 2,  states = {1,2,3,4},  states_weight = {30,40,20,10},  profession = {1001,1002,1003,1004,1005},  profession_weight = {10,10,10,10,10},  free_interval = 82800,  free_times = 1}

return data
