-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { index = 1,  order_name = "小丑",  spine_name = "XiaoChou",  icon_name = "js_03",  desc = "我和朋友要举行个生日派对，计划买点东西准备下"}
data[2] = { index = 2,  order_name = "医生",  spine_name = "YiSheng",  icon_name = "js_04",  desc = "想逗我的病人开心点，你有什么建议吗？"}
data[3] = { index = 3,  order_name = "厨师",  spine_name = "ChuShi",  icon_name = "js_01",  desc = "一位客人说我做的菜不好吃，我要想想新的食谱"}
data[4] = { index = 4,  order_name = "学生",  spine_name = "XueSheng",  icon_name = "js_02",  desc = "数学考试得了100分，耶~~妈妈奖励了我零花\n钱，可以去买自己喜欢的东西啦"}
data[5] = { index = 5,  order_name = "小男孩",  spine_name = "XiaoNanHai",  icon_name = "js_05",  desc = "我踢足球很厉害的哟~如果你帮我完成订单，\n我马上教你一点小技巧"}
data[6] = { index = 6,  order_name = "工人",  spine_name = "GongRen",  icon_name = "js_06",  desc = "为我们小镇作出贡献的时候到啦"}
data[7] = { index = 7,  order_name = "护士",  spine_name = "HuShi",  icon_name = "js_07",  desc = "我答应过一个小妹妹，等她康复了，我们一起\n做她喜欢的手工艺品"}
data[8] = { index = 8,  order_name = "站长",  spine_name = "ZhanZhang",  icon_name = "js_08",  desc = "小子，别耍花招，赶紧帮我送订单"}
data[9] = { index = 9,  order_name = "博士",  spine_name = "BoShi",  icon_name = "js_09",  desc = "我赶着去听讲座，时间快来不及了，麻烦你把\n东西送到我家"}
data[10] = { index = 10,  order_name = "家庭主妇",  spine_name = "JiaTingZhuFu",  icon_name = "js_10",  desc = "结婚纪念日快到了，我要准备好庆祝的礼物"}

return data
