-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { index = 1,  min_level = 1,  max_level = 2,  order_count = 1}
data[2] = { index = 2,  min_level = 3,  max_level = 4,  order_count = 2}
data[3] = { index = 3,  min_level = 5,  max_level = 6,  order_count = 3}
data[4] = { index = 4,  min_level = 7,  max_level = 8,  order_count = 4}
data[5] = { index = 5,  min_level = 9,  max_level = 10,  order_count = 5}
data[6] = { index = 6,  min_level = 11,  max_level = 12,  order_count = 6}
data[7] = { index = 7,  min_level = 13,  max_level = 14,  order_count = 6}
data[8] = { index = 8,  min_level = 15,  max_level = 1000,  order_count = 6}

return data
