-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { index = 1001,  name = "樱花岛",  finish_time = 14400,  need_gold = 70,  sale_multiple = {150,170,200,230,250},  multiple_weight = {20,20,20,20,20}}
data[1002] = { index = 1002,  name = "金砖岛",  finish_time = 14400,  need_gold = 80,  sale_multiple = {150,170,200,230,250,270},  multiple_weight = {10,20,20,20,20,10}}
data[1003] = { index = 1003,  name = "竞技岛",  finish_time = 18000,  need_gold = 90,  sale_multiple = {150,170,200,230,250,270,300},  multiple_weight = {10,20,20,20,10,10,10}}
data[1004] = { index = 1004,  name = "宝塔岛",  finish_time = 18000,  need_gold = 100,  sale_multiple = {150,170,200,230,250,270,300},  multiple_weight = {10,20,20,20,10,10,10}}
data[1005] = { index = 1005,  name = "迷宫岛",  finish_time = 25200,  need_gold = 110,  sale_multiple = {150,170,200,230,250,270,300},  multiple_weight = {10,10,10,10,20,20,20}}
data[1006] = { index = 1006,  name = "城墙岛",  finish_time = 25200,  need_gold = 120,  sale_multiple = {150,170,200,230,250,270,300},  multiple_weight = {10,10,10,10,20,20,20}}
data[1007] = { index = 1007,  name = "大厦岛",  finish_time = 28800,  need_gold = 130,  sale_multiple = {170,200,230,250,270,300},  multiple_weight = {10,10,20,20,20,20}}
data[1008] = { index = 1008,  name = "奇异岛",  finish_time = 28800,  need_gold = 140,  sale_multiple = {230,250,270,300},  multiple_weight = {20,20,30,30}}

return data
