-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1024] = { index = 1024,  item_index = 6012,  item_name = "龙虾",  reward_type = 2,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 33}
data[1025] = { index = 1025,  item_index = 6001,  item_name = "可可树",  reward_type = 3,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 8}
data[1026] = { index = 1026,  item_index = 6002,  item_name = "橡胶树",  reward_type = 3,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 11}
data[1027] = { index = 1027,  item_index = 6003,  item_name = "李子",  reward_type = 3,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 17}
data[1028] = { index = 1028,  item_index = 6004,  item_name = "水稻",  reward_type = 3,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 11}
data[1029] = { index = 1029,  item_index = 6005,  item_name = "橄榄",  reward_type = 3,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 16}
data[1030] = { index = 1030,  item_index = 6006,  item_name = "酸橙",  reward_type = 3,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 23}
data[1031] = { index = 1031,  item_index = 6007,  item_name = "香蕉",  reward_type = 3,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 16}
data[1032] = { index = 1032,  item_index = 6008,  item_name = "椰子",  reward_type = 3,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 22}
data[1033] = { index = 1033,  item_index = 6009,  item_name = "菠萝",  reward_type = 3,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 30}
data[1034] = { index = 1034,  item_index = 6010,  item_name = "鱼",  reward_type = 3,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 17}
data[1035] = { index = 1035,  item_index = 6011,  item_name = "虾",  reward_type = 3,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 24}
data[1036] = { index = 1036,  item_index = 6012,  item_name = "龙虾",  reward_type = 3,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 33}
data[1037] = { index = 1037,  item_index = 7001,  item_name = "金币",  reward_type = 4,  weight = 0,  unlock_level = 0,  item_count = {1},  count_weight = {1},  produce_exp = 0}
data[1001] = { index = 1001,  item_index = 6001,  item_name = "可可树",  reward_type = 1,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 8}
data[1002] = { index = 1002,  item_index = 6002,  item_name = "橡胶树",  reward_type = 1,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 11}
data[1003] = { index = 1003,  item_index = 6003,  item_name = "李子",  reward_type = 1,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 17}
data[1004] = { index = 1004,  item_index = 6004,  item_name = "水稻",  reward_type = 1,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 11}
data[1005] = { index = 1005,  item_index = 6005,  item_name = "橄榄",  reward_type = 1,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 16}
data[1006] = { index = 1006,  item_index = 6006,  item_name = "酸橙",  reward_type = 1,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 23}
data[1007] = { index = 1007,  item_index = 6007,  item_name = "香蕉",  reward_type = 1,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 16}
data[1008] = { index = 1008,  item_index = 6008,  item_name = "椰子",  reward_type = 1,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 22}
data[1009] = { index = 1009,  item_index = 6009,  item_name = "菠萝",  reward_type = 1,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 30}
data[1010] = { index = 1010,  item_index = 6010,  item_name = "鱼",  reward_type = 1,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 17}
data[1011] = { index = 1011,  item_index = 6011,  item_name = "虾",  reward_type = 1,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 24}
data[1012] = { index = 1012,  item_index = 6012,  item_name = "龙虾",  reward_type = 1,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 33}
data[1013] = { index = 1013,  item_index = 6001,  item_name = "可可树",  reward_type = 2,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 8}
data[1014] = { index = 1014,  item_index = 6002,  item_name = "橡胶树",  reward_type = 2,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 11}
data[1015] = { index = 1015,  item_index = 6003,  item_name = "李子",  reward_type = 2,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 17}
data[1016] = { index = 1016,  item_index = 6004,  item_name = "水稻",  reward_type = 2,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 11}
data[1017] = { index = 1017,  item_index = 6005,  item_name = "橄榄",  reward_type = 2,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 16}
data[1018] = { index = 1018,  item_index = 6006,  item_name = "酸橙",  reward_type = 2,  weight = 50,  unlock_level = 29,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 23}
data[1019] = { index = 1019,  item_index = 6007,  item_name = "香蕉",  reward_type = 2,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 16}
data[1020] = { index = 1020,  item_index = 6008,  item_name = "椰子",  reward_type = 2,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 22}
data[1021] = { index = 1021,  item_index = 6009,  item_name = "菠萝",  reward_type = 2,  weight = 50,  unlock_level = 41,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 30}
data[1022] = { index = 1022,  item_index = 6010,  item_name = "鱼",  reward_type = 2,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 17}
data[1023] = { index = 1023,  item_index = 6011,  item_name = "虾",  reward_type = 2,  weight = 50,  unlock_level = 52,  item_count = {1,2,3},  count_weight = {50,50,50},  produce_exp = 24}

return data
