-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { index = 1,  unlock_cash = 8}
data[2] = { index = 2,  unlock_cash = 8}
data[3] = { index = 3,  unlock_cash = 8}
data[4] = { index = 4,  unlock_cash = 9}
data[5] = { index = 5,  unlock_cash = 9}
data[6] = { index = 6,  unlock_cash = 9}
data[7] = { index = 7,  unlock_cash = 10}
data[8] = { index = 8,  unlock_cash = 10}
data[9] = { index = 9,  unlock_cash = 10}
data[10] = { index = 10,  unlock_cash = 11}
data[11] = { index = 11,  unlock_cash = 11}
data[12] = { index = 12,  unlock_cash = 12}
data[13] = { index = 13,  unlock_cash = 12}
data[14] = { index = 14,  unlock_cash = 13}
data[15] = { index = 15,  unlock_cash = 13}
data[16] = { index = 16,  unlock_cash = 14}
data[17] = { index = 17,  unlock_cash = 14}
data[18] = { index = 18,  unlock_cash = 15}
data[19] = { index = 19,  unlock_cash = 15}
data[20] = { index = 20,  unlock_cash = 16}
data[21] = { index = 21,  unlock_cash = 16}
data[22] = { index = 22,  unlock_cash = 17}
data[23] = { index = 23,  unlock_cash = 17}
data[24] = { index = 24,  unlock_cash = 18}
data[25] = { index = 25,  unlock_cash = 18}
data[26] = { index = 26,  unlock_cash = 19}
data[27] = { index = 27,  unlock_cash = 19}
data[28] = { index = 28,  unlock_cash = 20}
data[29] = { index = 29,  unlock_cash = 20}
data[30] = { index = 30,  unlock_cash = 21}
data[31] = { index = 31,  unlock_cash = 21}
data[32] = { index = 32,  unlock_cash = 22}
data[33] = { index = 33,  unlock_cash = 22}
data[34] = { index = 34,  unlock_cash = 23}
data[35] = { index = 35,  unlock_cash = 23}
data[36] = { index = 36,  unlock_cash = 24}
data[37] = { index = 37,  unlock_cash = 24}
data[38] = { index = 38,  unlock_cash = 25}
data[39] = { index = 39,  unlock_cash = 25}

return data
