-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1024] = { index = 1024,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 17,  order_weight = 10}
data[1025] = { index = 1025,  item_name = "金币",  item_index = 7001,  item_count = 1000,  type = 3,  unlock_level = 20,  order_weight = 20}
data[1026] = { index = 1026,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 20,  order_weight = 20}
data[1027] = { index = 1027,  item_name = "金币",  item_index = 7001,  item_count = 1500,  type = 3,  unlock_level = 25,  order_weight = 30}
data[1028] = { index = 1028,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 25,  order_weight = 30}
data[1029] = { index = 1029,  item_name = "金币",  item_index = 7001,  item_count = 2000,  type = 3,  unlock_level = 35,  order_weight = 40}
data[1030] = { index = 1030,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 35,  order_weight = 40}
data[1031] = { index = 1031,  item_name = "金币",  item_index = 7001,  item_count = 2500,  type = 3,  unlock_level = 45,  order_weight = 50}
data[1032] = { index = 1032,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 45,  order_weight = 50}
data[1033] = { index = 1033,  item_name = "金币",  item_index = 7001,  item_count = 3000,  type = 3,  unlock_level = 55,  order_weight = 60}
data[1034] = { index = 1034,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 55,  order_weight = 60}
data[1035] = { index = 1035,  item_name = "金币",  item_index = 7001,  item_count = 3500,  type = 3,  unlock_level = 65,  order_weight = 70}
data[1036] = { index = 1036,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 65,  order_weight = 70}
data[1037] = { index = 1037,  item_name = "金币",  item_index = 7001,  item_count = 4000,  type = 3,  unlock_level = 75,  order_weight = 80}
data[1038] = { index = 1038,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  unlock_level = 75,  order_weight = 80}
data[1039] = { index = 1039,  item_name = "金币",  item_index = 7001,  item_count = 4500,  type = 3,  unlock_level = 85,  order_weight = 90}
data[1040] = { index = 1040,  item_name = "钞票",  item_index = 7002,  item_count = 2,  type = 3,  unlock_level = 85,  order_weight = 90}
data[1041] = { index = 1041,  item_name = "金币",  item_index = 7001,  item_count = 5000,  type = 3,  unlock_level = 95,  order_weight = 100}
data[1042] = { index = 1042,  item_name = "钞票",  item_index = 7002,  item_count = 2,  type = 3,  unlock_level = 95,  order_weight = 100}
data[1043] = { index = 1043,  item_name = "金币",  item_index = 7001,  item_count = 5500,  type = 3,  unlock_level = 100,  order_weight = 110}
data[1044] = { index = 1044,  item_name = "钞票",  item_index = 7002,  item_count = 2,  type = 3,  unlock_level = 100,  order_weight = 110}
data[1001] = { index = 1001,  item_name = "黄宝石",  item_index = 3001,  item_count = 1,  type = 1,  unlock_level = 17,  order_weight = 40}
data[1002] = { index = 1002,  item_name = "绿宝石",  item_index = 3002,  item_count = 1,  type = 1,  unlock_level = 17,  order_weight = 30}
data[1003] = { index = 1003,  item_name = "红宝石",  item_index = 3003,  item_count = 1,  type = 1,  unlock_level = 17,  order_weight = 20}
data[1004] = { index = 1004,  item_name = "紫宝石",  item_index = 3004,  item_count = 1,  type = 1,  unlock_level = 17,  order_weight = 10}
data[1005] = { index = 1005,  item_name = "玻璃",  item_index = 5001,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 155}
data[1006] = { index = 1006,  item_name = "砖块",  item_index = 5002,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 155}
data[1007] = { index = 1007,  item_name = "水泥",  item_index = 5003,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 155}
data[1008] = { index = 1008,  item_name = "锤子",  item_index = 5004,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 45}
data[1009] = { index = 1009,  item_name = "钉子",  item_index = 5005,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 45}
data[1010] = { index = 1010,  item_name = "油漆",  item_index = 5006,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 45}
data[1011] = { index = 1011,  item_name = "铲子",  item_index = 5007,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 40}
data[1012] = { index = 1012,  item_name = "斧头",  item_index = 5008,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 32}
data[1013] = { index = 1013,  item_name = "锯子",  item_index = 5009,  item_count = 1,  type = 2,  unlock_level = 17,  order_weight = 28}
data[1014] = { index = 1014,  item_name = "玻璃",  item_index = 5001,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 155}
data[1015] = { index = 1015,  item_name = "砖块",  item_index = 5002,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 155}
data[1016] = { index = 1016,  item_name = "水泥",  item_index = 5003,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 155}
data[1017] = { index = 1017,  item_name = "锤子",  item_index = 5004,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 45}
data[1018] = { index = 1018,  item_name = "钉子",  item_index = 5005,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 45}
data[1019] = { index = 1019,  item_name = "油漆",  item_index = 5006,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 45}
data[1020] = { index = 1020,  item_name = "铲子",  item_index = 5007,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 40}
data[1021] = { index = 1021,  item_name = "斧头",  item_index = 5008,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 32}
data[1022] = { index = 1022,  item_name = "锯子",  item_index = 5009,  item_count = 2,  type = 2,  unlock_level = 30,  order_weight = 28}
data[1023] = { index = 1023,  item_name = "金币",  item_index = 7001,  item_count = 500,  type = 3,  unlock_level = 17,  order_weight = 10}

return data
