-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[2001] = { product_index = 2001,  product_name = "牛奶",  product_type = 2,  product_exp = 3,  formula = {4001},  formula_count = {1},  finish_time = 420,  unlock_level = 1}
data[2002] = { product_index = 2002,  product_name = "鸡蛋",  product_type = 2,  product_exp = 4,  formula = {4002},  formula_count = {1},  finish_time = 600,  unlock_level = 5}
data[2003] = { product_index = 2003,  product_name = "羊毛",  product_type = 2,  product_exp = 6,  formula = {4003},  formula_count = {1},  finish_time = 900,  unlock_level = 10}
data[2004] = { product_index = 2004,  product_name = "蜂巢",  product_type = 2,  product_exp = 6,  formula = {4004},  formula_count = {1},  finish_time = 1320,  unlock_level = 35}
data[2005] = { product_index = 2005,  product_name = "培根",  product_type = 2,  product_exp = 14,  formula = {4005},  formula_count = {1},  finish_time = 1920,  unlock_level = 42}

return data
