-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { product_index = 1001,  product_name = "高粱种植",  product_type = 1,  product_gold = 0,  product_exp = 1,  finish_time = 120,  unlock_level = 1}
data[1002] = { product_index = 1002,  product_name = "玉米种植",  product_type = 1,  product_gold = 1,  product_exp = 1,  finish_time = 300,  unlock_level = 3}
data[1003] = { product_index = 1003,  product_name = "胡萝卜种植",  product_type = 1,  product_gold = 2,  product_exp = 2,  finish_time = 600,  unlock_level = 4}
data[1004] = { product_index = 1004,  product_name = "甜菜种植",  product_type = 1,  product_gold = 3,  product_exp = 3,  finish_time = 1200,  unlock_level = 7}
data[1005] = { product_index = 1005,  product_name = "棉花种植",  product_type = 1,  product_gold = 4,  product_exp = 4,  finish_time = 1800,  unlock_level = 9}
data[1006] = { product_index = 1006,  product_name = "草莓种植",  product_type = 1,  product_gold = 5,  product_exp = 5,  finish_time = 3600,  unlock_level = 12}
data[1007] = { product_index = 1007,  product_name = "番茄种植",  product_type = 1,  product_gold = 6,  product_exp = 6,  finish_time = 7200,  unlock_level = 15}
data[1008] = { product_index = 1008,  product_name = "杨树种植",  product_type = 1,  product_gold = 7,  product_exp = 7,  finish_time = 10800,  unlock_level = 18}
data[1009] = { product_index = 1009,  product_name = "土豆种植",  product_type = 1,  product_gold = 8,  product_exp = 8,  finish_time = 14400,  unlock_level = 22}
data[1010] = { product_index = 1010,  product_name = "葡萄种植",  product_type = 1,  product_gold = 7,  product_exp = 5,  finish_time = 4800,  unlock_level = 35}
data[1011] = { product_index = 1011,  product_name = "艾得来丝绸种植",  product_type = 1,  product_gold = 20,  product_exp = 14,  finish_time = 54000,  unlock_level = 31}
data[1012] = { product_index = 1012,  product_name = "辣椒种植",  product_type = 1,  product_gold = 11,  product_exp = 9,  finish_time = 18000,  unlock_level = 43}
data[1013] = { product_index = 1013,  product_name = "红玫瑰种植",  product_type = 1,  product_gold = 18,  product_exp = 7,  finish_time = 9000,  unlock_level = 61}
data[1014] = { product_index = 1014,  product_name = "西瓜种植",  product_type = 1,  product_gold = 15,  product_exp = 13,  finish_time = 43200,  unlock_level = 29}
data[1015] = { product_index = 1015,  product_name = "新疆桃种植",  product_type = 1,  product_gold = 9,  product_exp = 11,  finish_time = 28800,  unlock_level = 25}

return data
