-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { index = 1,  word = "SB"}
data[2] = { index = 2,  word = "sb"}
data[3] = { index = 3,  word = "fuck"}
data[4] = { index = 4,  word = "煞笔"}
data[5] = { index = 5,  word = "傻逼"}
data[6] = { index = 6,  word = "傻b"}
data[7] = { index = 7,  word = "傻B"}
data[8] = { index = 8,  word = "妈的"}
data[9] = { index = 9,  word = "傻"}
data[10] = { index = 10,  word = "逼"}
data[11] = { index = 11,  word = "妈逼"}
data[12] = { index = 12,  word = "妈b"}
data[13] = { index = 13,  word = "妈B"}
data[14] = { index = 14,  word = "shit"}
data[15] = { index = 15,  word = "屎"}
data[16] = { index = 16,  word = "尿"}
data[17] = { index = 17,  word = "草"}
data[18] = { index = 18,  word = "艹"}
data[19] = { index = 19,  word = "屌"}
data[20] = { index = 20,  word = "jb"}
data[21] = { index = 21,  word = "JB"}
data[22] = { index = 22,  word = "大爷"}
data[23] = { index = 23,  word = "老母"}
data[24] = { index = 24,  word = "操"}
data[25] = { index = 25,  word = "肏"}
data[26] = { index = 26,  word = "日你"}
data[27] = { index = 27,  word = "曰你"}
data[28] = { index = 28,  word = "奸"}
data[29] = { index = 29,  word = "性交"}
data[30] = { index = 30,  word = "性侵"}

return data
