-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1024] = { index = 1024,  daytimes = 4,  type = 6,  total = 10,  items = {},  items_count = {},  exp = 0,  title = "发送火车"}
data[1025] = { index = 1025,  daytimes = 4,  type = 6,  total = 15,  items = {},  items_count = {},  exp = 0,  title = "发送火车"}
data[1026] = { index = 1026,  daytimes = 5,  type = 7,  total = 5,  items = {},  items_count = {},  exp = 0,  title = "拥有好友"}
data[1027] = { index = 1027,  daytimes = 5,  type = 7,  total = 10,  items = {},  items_count = {},  exp = 0,  title = "拥有好友"}
data[1028] = { index = 1028,  daytimes = 5,  type = 7,  total = 20,  items = {},  items_count = {},  exp = 0,  title = "拥有好友"}
data[1029] = { index = 1029,  daytimes = 5,  type = 8,  total = 5,  items = {},  items_count = {},  exp = 0,  title = "帮助好友火车订单"}
data[1030] = { index = 1030,  daytimes = 5,  type = 9,  total = 30,  items = {},  items_count = {},  exp = 0,  title = "帮助好友浇水"}
data[1031] = { index = 1031,  daytimes = 6,  type = 10,  total = 1,  items = {},  items_count = {},  exp = 0,  title = "扩充仓库"}
data[1032] = { index = 1032,  daytimes = 6,  type = 10,  total = 2,  items = {},  items_count = {},  exp = 0,  title = "扩充仓库"}
data[1033] = { index = 1033,  daytimes = 6,  type = 10,  total = 5,  items = {},  items_count = {},  exp = 0,  title = "扩充仓库"}
data[1034] = { index = 1034,  daytimes = 6,  type = 10,  total = 10,  items = {},  items_count = {},  exp = 0,  title = "扩充仓库"}
data[1035] = { index = 1035,  daytimes = 6,  type = 10,  total = 15,  items = {},  items_count = {},  exp = 0,  title = "扩充仓库"}
data[1036] = { index = 1036,  daytimes = 7,  type = 11,  total = 2,  items = {},  items_count = {},  exp = 0,  title = "扩建未开放区域"}
data[1037] = { index = 1037,  daytimes = 7,  type = 11,  total = 6,  items = {},  items_count = {},  exp = 0,  title = "扩建未开放区域"}
data[1038] = { index = 1038,  daytimes = 7,  type = 11,  total = 10,  items = {},  items_count = {},  exp = 0,  title = "扩建未开放区域"}
data[1039] = { index = 1039,  daytimes = 7,  type = 11,  total = 14,  items = {},  items_count = {},  exp = 0,  title = "扩建未开放区域"}
data[1040] = { index = 1040,  daytimes = 7,  type = 11,  total = 18,  items = {},  items_count = {},  exp = 0,  title = "扩建未开放区域"}
data[1041] = { index = 1041,  daytimes = 7,  type = 12,  total = 2,  items = {},  items_count = {},  exp = 0,  title = "建造装饰物"}
data[1042] = { index = 1042,  daytimes = 7,  type = 12,  total = 5,  items = {},  items_count = {},  exp = 0,  title = "建造装饰物"}
data[1043] = { index = 1043,  daytimes = 7,  type = 12,  total = 10,  items = {},  items_count = {},  exp = 0,  title = "建造装饰物"}
data[1001] = { index = 1001,  daytimes = 1,  type = 1,  total = 10,  items = {7001,7002},  items_count = {10,10},  exp = 300,  title = "收割农作物"}
data[1002] = { index = 1002,  daytimes = 1,  type = 1,  total = 30,  items = {7001,7002},  items_count = {10,10},  exp = 300,  title = "收割农作物"}
data[1003] = { index = 1003,  daytimes = 1,  type = 1,  total = 60,  items = {},  items_count = {},  exp = 0,  title = "收割农作物"}
data[1004] = { index = 1004,  daytimes = 1,  type = 1,  total = 100,  items = {},  items_count = {},  exp = 0,  title = "收割农作物"}
data[1005] = { index = 1005,  daytimes = 1,  type = 2,  total = 5,  items = {},  items_count = {},  exp = 0,  title = "收获工厂物品"}
data[1006] = { index = 1006,  daytimes = 1,  type = 2,  total = 10,  items = {},  items_count = {},  exp = 0,  title = "收获工厂物品"}
data[1007] = { index = 1007,  daytimes = 1,  type = 2,  total = 20,  items = {},  items_count = {},  exp = 0,  title = "收获工厂物品"}
data[1008] = { index = 1008,  daytimes = 1,  type = 2,  total = 50,  items = {},  items_count = {},  exp = 0,  title = "收获工厂物品"}
data[1009] = { index = 1009,  daytimes = 2,  type = 3,  total = 5,  items = {},  items_count = {},  exp = 0,  title = "达到等级"}
data[1010] = { index = 1010,  daytimes = 2,  type = 3,  total = 10,  items = {},  items_count = {},  exp = 0,  title = "达到等级"}
data[1011] = { index = 1011,  daytimes = 2,  type = 3,  total = 20,  items = {},  items_count = {},  exp = 0,  title = "达到等级"}
data[1012] = { index = 1012,  daytimes = 2,  type = 3,  total = 30,  items = {},  items_count = {},  exp = 0,  title = "达到等级"}
data[1013] = { index = 1013,  daytimes = 2,  type = 4,  total = 200,  items = {},  items_count = {},  exp = 0,  title = "达到人口数量"}
data[1014] = { index = 1014,  daytimes = 2,  type = 4,  total = 300,  items = {},  items_count = {},  exp = 0,  title = "达到人口数量"}
data[1015] = { index = 1015,  daytimes = 2,  type = 4,  total = 400,  items = {},  items_count = {},  exp = 0,  title = "达到人口数量"}
data[1016] = { index = 1016,  daytimes = 3,  type = 5,  total = 1,  items = {},  items_count = {},  exp = 0,  title = "完成直升机订单"}
data[1017] = { index = 1017,  daytimes = 3,  type = 5,  total = 3,  items = {},  items_count = {},  exp = 0,  title = "完成直升机订单"}
data[1018] = { index = 1018,  daytimes = 3,  type = 5,  total = 7,  items = {},  items_count = {},  exp = 0,  title = "完成直升机订单"}
data[1019] = { index = 1019,  daytimes = 3,  type = 5,  total = 15,  items = {},  items_count = {},  exp = 0,  title = "完成直升机订单"}
data[1020] = { index = 1020,  daytimes = 3,  type = 5,  total = 30,  items = {},  items_count = {},  exp = 0,  title = "完成直升机订单"}
data[1021] = { index = 1021,  daytimes = 4,  type = 6,  total = 1,  items = {},  items_count = {},  exp = 0,  title = "发送火车"}
data[1022] = { index = 1022,  daytimes = 4,  type = 6,  total = 3,  items = {},  items_count = {},  exp = 0,  title = "发送火车"}
data[1023] = { index = 1023,  daytimes = 4,  type = 6,  total = 5,  items = {},  items_count = {},  exp = 0,  title = "发送火车"}

return data
