-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { index = 1001,  type = 1,  price = 1,  count = 100,  icon = ""}
data[1002] = { index = 1002,  type = 1,  price = 6,  count = 600,  icon = ""}
data[1003] = { index = 1003,  type = 1,  price = 30,  count = 3000,  icon = ""}
data[1004] = { index = 1004,  type = 1,  price = 60,  count = 6000,  icon = ""}
data[1005] = { index = 1005,  type = 1,  price = 100,  count = 10000,  icon = ""}
data[1006] = { index = 1006,  type = 1,  price = 200,  count = 20000,  icon = ""}
data[1007] = { index = 1007,  type = 1,  price = 300,  count = 30000,  icon = ""}
data[1008] = { index = 1008,  type = 1,  price = 600,  count = 60000,  icon = ""}
data[1009] = { index = 1009,  type = 2,  price = 1,  count = 10,  icon = ""}
data[1010] = { index = 1010,  type = 2,  price = 6,  count = 60,  icon = ""}
data[1011] = { index = 1011,  type = 2,  price = 30,  count = 300,  icon = ""}
data[1012] = { index = 1012,  type = 2,  price = 60,  count = 600,  icon = ""}
data[1013] = { index = 1013,  type = 2,  price = 100,  count = 1000,  icon = ""}
data[1014] = { index = 1014,  type = 2,  price = 200,  count = 2000,  icon = ""}
data[1015] = { index = 1015,  type = 2,  price = 300,  count = 3000,  icon = ""}
data[1016] = { index = 1016,  type = 2,  price = 600,  count = 6000,  icon = ""}

return data
