-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { day = 1,  coin_count = 250}
data[2] = { day = 2,  coin_count = 500}
data[3] = { day = 3,  coin_count = 1000}
data[4] = { day = 4,  coin_count = 1500}

return data
