-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { index = 1001,  item_name = "玻璃",  item_index = 5001,  item_count = 1,  type = 1,  weight = 10}
data[1002] = { index = 1002,  item_name = "砖块",  item_index = 5002,  item_count = 1,  type = 1,  weight = 10}
data[1003] = { index = 1003,  item_name = "水泥",  item_index = 5003,  item_count = 1,  type = 1,  weight = 10}
data[1004] = { index = 1004,  item_name = "锤子",  item_index = 5004,  item_count = 1,  type = 1,  weight = 10}
data[1005] = { index = 1005,  item_name = "钉子",  item_index = 5005,  item_count = 1,  type = 1,  weight = 10}
data[1006] = { index = 1006,  item_name = "油漆",  item_index = 5006,  item_count = 1,  type = 1,  weight = 10}
data[1007] = { index = 1007,  item_name = "铲子",  item_index = 5007,  item_count = 1,  type = 2,  weight = 10}
data[1008] = { index = 1008,  item_name = "斧头",  item_index = 5008,  item_count = 1,  type = 2,  weight = 10}
data[1009] = { index = 1009,  item_name = "锯子",  item_index = 5009,  item_count = 1,  type = 2,  weight = 10}
data[1010] = { index = 1010,  item_name = "金币",  item_index = 7001,  item_count = 2000,  type = 3,  weight = 10}
data[1011] = { index = 1011,  item_name = "钞票",  item_index = 7002,  item_count = 1,  type = 3,  weight = 10}

return data
