-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { index = 1,  cash = 1,  time = 300}
data[2] = { index = 2,  cash = 2,  time = 780}
data[3] = { index = 3,  cash = 3,  time = 1500}
data[4] = { index = 4,  cash = 4,  time = 3000}
data[5] = { index = 5,  cash = 5,  time = 4800}
data[6] = { index = 6,  cash = 6,  time = 7200}
data[7] = { index = 7,  cash = 7,  time = 10800}
data[8] = { index = 8,  cash = 8,  time = 14400}
data[9] = { index = 9,  cash = 9,  time = 19800}
data[10] = { index = 10,  cash = 10,  time = 25200}
data[11] = { index = 11,  cash = 11,  time = 30600}
data[12] = { index = 12,  cash = 12,  time = 41400}
data[13] = { index = 13,  cash = 13,  time = 52200}
data[14] = { index = 14,  cash = 14,  time = 63000}
data[15] = { index = 15,  cash = 15,  time = 77400}
data[16] = { index = 16,  cash = 16,  time = 91800}
data[17] = { index = 17,  cash = 17,  time = 113400}
data[18] = { index = 18,  cash = 18,  time = 135000}
data[19] = { index = 19,  cash = 19,  time = 156600}
data[20] = { index = 20,  cash = 20,  time = 185400}
data[21] = { index = 21,  cash = 21,  time = 214200}
data[22] = { index = 22,  cash = 22,  time = 243000}
data[23] = { index = 23,  cash = 23,  time = 279000}
data[24] = { index = 24,  cash = 24,  time = 315000}
data[25] = { index = 25,  cash = 25,  time = 351000}
data[26] = { index = 26,  cash = 26,  time = 394200}

return data
