-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[32001] = { spine_index = 32001,  spine_name = "buildConstruction",  spinedesc = "建造中",  spine_type = 3,  spine_anims = {},  spine_anims_desc = {}}
data[32002] = { spine_index = 32002,  spine_name = "buildComplete",  spinedesc = "建造完成",  spine_type = 3,  spine_anims = {},  spine_anims_desc = {}}
data[21001] = { spine_index = 21001,  spine_name = "wheat",  spinedesc = "小麦",  spine_type = 2,  spine_anims = {"state1,state2,state3,state4"},  spine_anims_desc = {}}
data[21002] = { spine_index = 21002,  spine_name = "corn",  spinedesc = "玉米",  spine_type = 2,  spine_anims = {"state1,state2,state3,state5"},  spine_anims_desc = {}}
data[21003] = { spine_index = 21003,  spine_name = "carrot",  spinedesc = "胡萝卜",  spine_type = 2,  spine_anims = {"state1,state2,state3,state6"},  spine_anims_desc = {}}
data[21004] = { spine_index = 21004,  spine_name = "beet",  spinedesc = "甜菜",  spine_type = 2,  spine_anims = {"state1,state2,state3,state7"},  spine_anims_desc = {}}
data[21005] = { spine_index = 21005,  spine_name = "cotton",  spinedesc = "棉花",  spine_type = 2,  spine_anims = {"state1,state2,state3,state8"},  spine_anims_desc = {}}
data[21006] = { spine_index = 21006,  spine_name = "strawberry",  spinedesc = "草莓",  spine_type = 2,  spine_anims = {"state1,state2,state3,state9"},  spine_anims_desc = {}}
data[21007] = { spine_index = 21007,  spine_name = "tomato",  spinedesc = "番茄",  spine_type = 2,  spine_anims = {"state1,state2,state3,state10"},  spine_anims_desc = {}}
data[21008] = { spine_index = 21008,  spine_name = "poplar",  spinedesc = "杨树",  spine_type = 2,  spine_anims = {"state1,state2,state3,state11"},  spine_anims_desc = {}}
data[21009] = { spine_index = 21009,  spine_name = "potato",  spinedesc = "土豆",  spine_type = 2,  spine_anims = {"state1,state2,state3,state12"},  spine_anims_desc = {}}
data[21010] = { spine_index = 21010,  spine_name = "grape",  spinedesc = "葡萄",  spine_type = 2,  spine_anims = {"state1,state2,state3,state13"},  spine_anims_desc = {}}
data[21011] = { spine_index = 21011,  spine_name = "rubberTree",  spinedesc = "橡胶树",  spine_type = 2,  spine_anims = {"state1,state2,state3,state14"},  spine_anims_desc = {}}
data[21012] = { spine_index = 21012,  spine_name = "silk",  spinedesc = "艾得来丝绸",  spine_type = 2,  spine_anims = {"state1,state2,state3,state15"},  spine_anims_desc = {}}
data[21013] = { spine_index = 21013,  spine_name = "chili",  spinedesc = "辣椒",  spine_type = 2,  spine_anims = {"state1,state2,state3,state16"},  spine_anims_desc = {}}
data[21014] = { spine_index = 21014,  spine_name = "rice",  spinedesc = "水稻",  spine_type = 2,  spine_anims = {"state1,state2,state3,state17"},  spine_anims_desc = {}}
data[21015] = { spine_index = 21015,  spine_name = "redRose",  spinedesc = "红玫瑰",  spine_type = 2,  spine_anims = {"state1,state2,state3,state18"},  spine_anims_desc = {}}
data[11001] = { spine_index = 11001,  spine_name = "farmer",  spinedesc = "农夫",  spine_type = 1,  spine_anims = {"state1,state2,state3,state4"},  spine_anims_desc = {}}

return data
