-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { spint_index = 1,  spint_name = "名称",  anim_name = "JS_1_JingChe",  type = 1,  level = 0,  open = 1}
data[2] = { spint_index = 2,  spint_name = "名称",  anim_name = "JS_2_XiaoHuangChe",  type = 1,  level = 0,  open = 1}
data[3] = { spint_index = 3,  spint_name = "名称",  anim_name = "JS_11_DaBa",  type = 1,  level = 0,  open = 1}
data[4] = { spint_index = 4,  spint_name = "名称",  anim_name = "JS_12_BingQiLinChe",  type = 1,  level = 0,  open = 1}
data[5] = { spint_index = 5,  spint_name = "名称",  anim_name = "JS_13_JiuHuChe",  type = 1,  level = 0,  open = 1}
data[6] = { spint_index = 6,  spint_name = "名称",  anim_name = "JS_14_XiangShi",  type = 1,  level = 0,  open = 1}
data[7] = { spint_index = 7,  spint_name = "名称",  anim_name = "JS_15_XiaoFangChe",  type = 1,  level = 0,  open = 1}
data[8] = { spint_index = 8,  spint_name = "名称",  anim_name = "JS_17_LaHuoChe",  type = 1,  level = 0,  open = 1}
data[9] = { spint_index = 9,  spint_name = "名称",  anim_name = "JS_18_KaFeiChe",  type = 1,  level = 0,  open = 1}
data[10] = { spint_index = 10,  spint_name = "名称",  anim_name = "JS_3_ZhenZhan",  type = 2,  level = 0,  open = 1}
data[11] = { spint_index = 11,  spint_name = "名称",  anim_name = "JS_6_FeiPo",  type = 2,  level = 0,  open = 1}
data[12] = { spint_index = 12,  spint_name = "名称",  anim_name = "JS_7_BanGongNv",  type = 2,  level = 0,  open = 1}
data[13] = { spint_index = 13,  spint_name = "名称",  anim_name = "JS_8_LaoPoPo",  type = 2,  level = 0,  open = 1}
data[14] = { spint_index = 14,  spint_name = "名称",  anim_name = "JS_9_KongLong",  type = 2,  level = 0,  open = 1}
data[15] = { spint_index = 15,  spint_name = "名称",  anim_name = "JS_10_AFanTi",  type = 2,  level = 0,  open = 1}
data[16] = { spint_index = 16,  spint_name = "名称",  anim_name = "JS_31_ShenShi",  type = 2,  level = 0,  open = 1}
data[17] = { spint_index = 17,  spint_name = "名称",  anim_name = "JS_32_YouChai",  type = 2,  level = 0,  open = 1}
data[18] = { spint_index = 18,  spint_name = "名称",  anim_name = "JS_33_YiRen",  type = 2,  level = 0,  open = 1}
data[19] = { spint_index = 19,  spint_name = "名称",  anim_name = "JS_34_XiaoChou",  type = 2,  level = 0,  open = 1}
data[20] = { spint_index = 20,  spint_name = "名称",  anim_name = "JS_35_GaoZhongSheng",  type = 2,  level = 0,  open = 1}
data[21] = { spint_index = 21,  spint_name = "名称",  anim_name = "JS_29_TuoNiao",  type = 3,  level = 0,  open = 1}
data[22] = { spint_index = 22,  spint_name = "名称",  anim_name = "JS_30_MaoYou",  type = 3,  level = 0,  open = 1}
data[23] = { spint_index = 23,  spint_name = "名称",  anim_name = "JS_28_XiYi",  type = 3,  level = 0,  open = 1}

return data
