-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { index = 1001,  type = 1,  desc = "完成的订单",  icon = "icon_101"}
data[1002] = { index = 1002,  type = 2,  desc = "已发火车",  icon = "icon_104"}
data[1003] = { index = 1003,  type = 3,  desc = "满载飞机已发送",  icon = "icon_128"}
data[1004] = { index = 1004,  type = 4,  desc = "船只已发送",  icon = "icon_130"}
data[1005] = { index = 1005,  type = 5,  desc = "生产的产品",  icon = "icon_103"}

return data
