-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { index = 1,  terminal_name = "印度",  unlock_level = 5,  travel_time = 300,  terminal_weight = 10}
data[2] = { index = 2,  terminal_name = "泰国",  unlock_level = 5,  travel_time = 300,  terminal_weight = 20}
data[3] = { index = 3,  terminal_name = "伊朗",  unlock_level = 5,  travel_time = 300,  terminal_weight = 30}
data[4] = { index = 4,  terminal_name = "俄罗斯",  unlock_level = 10,  travel_time = 600,  terminal_weight = 40}
data[5] = { index = 5,  terminal_name = "土耳其",  unlock_level = 10,  travel_time = 600,  terminal_weight = 50}
data[6] = { index = 6,  terminal_name = "乌克兰",  unlock_level = 10,  travel_time = 300,  terminal_weight = 60}
data[7] = { index = 7,  terminal_name = "韩国",  unlock_level = 13,  travel_time = 900,  terminal_weight = 70}
data[8] = { index = 8,  terminal_name = "日本",  unlock_level = 13,  travel_time = 900,  terminal_weight = 80}
data[9] = { index = 9,  terminal_name = "埃及",  unlock_level = 13,  travel_time = 600,  terminal_weight = 90}
data[10] = { index = 10,  terminal_name = "瑞典",  unlock_level = 16,  travel_time = 1200,  terminal_weight = 100}
data[11] = { index = 11,  terminal_name = "瑞士",  unlock_level = 16,  travel_time = 900,  terminal_weight = 110}
data[12] = { index = 12,  terminal_name = "意大利",  unlock_level = 16,  travel_time = 600,  terminal_weight = 120}
data[13] = { index = 13,  terminal_name = "法国",  unlock_level = 21,  travel_time = 3600,  terminal_weight = 130}
data[14] = { index = 14,  terminal_name = "德国",  unlock_level = 21,  travel_time = 1800,  terminal_weight = 140}
data[15] = { index = 15,  terminal_name = "比利时",  unlock_level = 21,  travel_time = 900,  terminal_weight = 150}
data[16] = { index = 16,  terminal_name = "英国",  unlock_level = 27,  travel_time = 7200,  terminal_weight = 160}
data[17] = { index = 17,  terminal_name = "荷兰",  unlock_level = 27,  travel_time = 3600,  terminal_weight = 170}
data[18] = { index = 18,  terminal_name = "西班牙",  unlock_level = 27,  travel_time = 1800,  terminal_weight = 180}
data[19] = { index = 19,  terminal_name = "葡萄牙",  unlock_level = 34,  travel_time = 10800,  terminal_weight = 190}
data[20] = { index = 20,  terminal_name = "克罗地亚",  unlock_level = 34,  travel_time = 7200,  terminal_weight = 200}
data[21] = { index = 21,  terminal_name = "南非",  unlock_level = 34,  travel_time = 3600,  terminal_weight = 210}
data[22] = { index = 22,  terminal_name = "澳大利亚",  unlock_level = 45,  travel_time = 14400,  terminal_weight = 220}
data[23] = { index = 23,  terminal_name = "冰岛",  unlock_level = 45,  travel_time = 10800,  terminal_weight = 230}
data[24] = { index = 24,  terminal_name = "美国",  unlock_level = 45,  travel_time = 7200,  terminal_weight = 240}
data[25] = { index = 25,  terminal_name = "加拿大",  unlock_level = 55,  travel_time = 18000,  terminal_weight = 250}
data[26] = { index = 26,  terminal_name = "巴西",  unlock_level = 55,  travel_time = 14400,  terminal_weight = 260}
data[27] = { index = 27,  terminal_name = "阿根廷",  unlock_level = 55,  travel_time = 10800,  terminal_weight = 270}
data[28] = { index = 28,  terminal_name = "墨西哥",  unlock_level = 60,  travel_time = 21600,  terminal_weight = 280}
data[29] = { index = 29,  terminal_name = "智利",  unlock_level = 60,  travel_time = 18000,  terminal_weight = 290}
data[30] = { index = 30,  terminal_name = "哥伦比亚",  unlock_level = 60,  travel_time = 14400,  terminal_weight = 300}

return data
