-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { reward_index = 1001,  reward_name = "玻璃",  reward_item = 5001,  reward_count = 1,  reward_weight = 120,  unlock_level = 1}
data[1002] = { reward_index = 1002,  reward_name = "砖块",  reward_item = 5002,  reward_count = 1,  reward_weight = 120,  unlock_level = 1}
data[1003] = { reward_index = 1003,  reward_name = "水泥",  reward_item = 5003,  reward_count = 1,  reward_weight = 120,  unlock_level = 1}
data[1004] = { reward_index = 1004,  reward_name = "铁锤",  reward_item = 5004,  reward_count = 1,  reward_weight = 80,  unlock_level = 1}
data[1005] = { reward_index = 1005,  reward_name = "钉子",  reward_item = 5005,  reward_count = 1,  reward_weight = 80,  unlock_level = 1}
data[1006] = { reward_index = 1006,  reward_name = "油漆",  reward_item = 5006,  reward_count = 1,  reward_weight = 80,  unlock_level = 1}
data[1007] = { reward_index = 1007,  reward_name = "铲子",  reward_item = 5007,  reward_count = 1,  reward_weight = 40,  unlock_level = 13}
data[1008] = { reward_index = 1008,  reward_name = "斧头",  reward_item = 5008,  reward_count = 1,  reward_weight = 32,  unlock_level = 18}
data[1009] = { reward_index = 1009,  reward_name = "锯子",  reward_item = 5009,  reward_count = 1,  reward_weight = 28,  unlock_level = 24}

return data
