-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { trains_index = 1001,  trains_name = "trains001",  trains_conditions = {"level","money"},  condition_counts = {5,0}}
data[1002] = { trains_index = 1002,  trains_name = "trains002",  trains_conditions = {"level","money"},  condition_counts = {14,1000}}
data[1003] = { trains_index = 1003,  trains_name = "trains003",  trains_conditions = {"level","money"},  condition_counts = {25,14000}}

return data
