-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { index_id = 1,  profession = "农民",  profession_index = 1001,  star_id = 1,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {2,2,0,0}}
data[2] = { index_id = 2,  profession = "农民",  profession_index = 1001,  star_id = 2,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0,3,2,0}}
data[3] = { index_id = 3,  profession = "农民",  profession_index = 1001,  star_id = 3,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {3,2,3,1}}
data[4] = { index_id = 4,  profession = "农民",  profession_index = 1001,  star_id = 4,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {5,6,2,2}}
data[5] = { index_id = 5,  profession = "农民",  profession_index = 1001,  star_id = 5,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0}}
data[6] = { index_id = 6,  profession = "饲养员",  profession_index = 1002,  star_id = 1,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {3,0,1,0}}
data[7] = { index_id = 7,  profession = "饲养员",  profession_index = 1002,  star_id = 2,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {1,3,0,1}}
data[8] = { index_id = 8,  profession = "饲养员",  profession_index = 1002,  star_id = 3,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0,3,5,0}}
data[9] = { index_id = 9,  profession = "饲养员",  profession_index = 1002,  star_id = 4,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {4,4,2,3}}
data[10] = { index_id = 10,  profession = "饲养员",  profession_index = 1002,  star_id = 5,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0}}
data[11] = { index_id = 11,  profession = "运输员",  profession_index = 1003,  star_id = 1,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {4,1,0,0}}
data[12] = { index_id = 12,  profession = "运输员",  profession_index = 1003,  star_id = 2,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {3,3,1,0}}
data[13] = { index_id = 13,  profession = "运输员",  profession_index = 1003,  star_id = 3,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0,5,2,1}}
data[14] = { index_id = 14,  profession = "运输员",  profession_index = 1003,  star_id = 4,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {4,5,3,2}}
data[15] = { index_id = 15,  profession = "运输员",  profession_index = 1003,  star_id = 5,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0}}
data[16] = { index_id = 16,  profession = "商人",  profession_index = 1004,  star_id = 1,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {6,0,0,0}}
data[17] = { index_id = 17,  profession = "商人",  profession_index = 1004,  star_id = 2,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {5,2,1,0}}
data[18] = { index_id = 18,  profession = "商人",  profession_index = 1004,  star_id = 3,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {4,4,3,0}}
data[19] = { index_id = 19,  profession = "商人",  profession_index = 1004,  star_id = 4,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {6,4,3,2}}
data[20] = { index_id = 20,  profession = "商人",  profession_index = 1004,  star_id = 5,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0}}
data[21] = { index_id = 21,  profession = "工人",  profession_index = 1005,  star_id = 1,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {1,1,1,0}}
data[22] = { index_id = 22,  profession = "工人",  profession_index = 1005,  star_id = 2,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {2,5,0,0}}
data[23] = { index_id = 23,  profession = "工人",  profession_index = 1005,  star_id = 3,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0,1,3,2}}
data[24] = { index_id = 24,  profession = "工人",  profession_index = 1005,  star_id = 4,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {1,0,4,4}}
data[25] = { index_id = 25,  profession = "工人",  profession_index = 1005,  star_id = 5,  starup_require = {"topaz","emerald","ruby","amethyst"},  starup_count = {0}}

return data
