-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1001] = { worker_index = 1001,  worker_name = "戴名人",  worker_icon = "Js_Bs_01",  worker_min_icon = "Js_Gy_01",  worker_head = "Js_Gy_01",  worker_type = {1001,1002,1003,1004,1005}}
data[1002] = { worker_index = 1002,  worker_name = "小红",  worker_icon = "Js_Bs_02",  worker_min_icon = "Js_Gy_02",  worker_head = "Js_Gy_02",  worker_type = {1001,1002,1003,1004,1005}}
data[1003] = { worker_index = 1003,  worker_name = "麦基德",  worker_icon = "Js_Bs_03",  worker_min_icon = "Js_Gy_03",  worker_head = "Js_Gy_03",  worker_type = {1001,1002,1003,1004,1005}}
data[1004] = { worker_index = 1004,  worker_name = "小野",  worker_icon = "Js_Bs_04",  worker_min_icon = "Js_Gy_04",  worker_head = "Js_Gy_04",  worker_type = {1001,1002,1003,1004,1005}}
data[1005] = { worker_index = 1005,  worker_name = "金灿灿",  worker_icon = "Js_Bs_06",  worker_min_icon = "Js_Gy_06",  worker_head = "Js_Gy_06",  worker_type = {1001,1002,1003,1004,1005}}
data[1006] = { worker_index = 1006,  worker_name = "丘比",  worker_icon = "Js_Bs_07",  worker_min_icon = "Js_Gy_07",  worker_head = "Js_Gy_07",  worker_type = {1001,1002,1003,1004,1005}}
data[1007] = { worker_index = 1007,  worker_name = "老蓝",  worker_icon = "Js_Bs_08",  worker_min_icon = "Js_Gy_08",  worker_head = "Js_Gy_08",  worker_type = {1001,1002,1003,1004,1005}}
data[1008] = { worker_index = 1008,  worker_name = "小博",  worker_icon = "Js_Bs_09",  worker_min_icon = "Js_Gy_09",  worker_head = "Js_Gy_09",  worker_type = {1001,1002,1003,1004,1005}}
data[1009] = { worker_index = 1009,  worker_name = "黄阿依",  worker_icon = "Js_Bs_10",  worker_min_icon = "Js_Gy_10",  worker_head = "Js_Gy_10",  worker_type = {1001,1002,1003,1004,1005}}
data[1010] = { worker_index = 1010,  worker_name = "艾尼",  worker_icon = "Js_Bs_11",  worker_min_icon = "Js_Gy_11",  worker_head = "Js_Gy_11",  worker_type = {1001,1002,1003,1004,1005}}
data[1011] = { worker_index = 1011,  worker_name = "戴名人",  worker_icon = "Js_Bs_01",  worker_min_icon = "Js_Gy_01",  worker_head = "Js_Gy_01",  worker_type = {1001,1002,1003,1004,1005}}
data[1012] = { worker_index = 1012,  worker_name = "小红",  worker_icon = "Js_Bs_02",  worker_min_icon = "Js_Gy_02",  worker_head = "Js_Gy_02",  worker_type = {1001,1002,1003,1004,1005}}
data[1013] = { worker_index = 1013,  worker_name = "麦基德",  worker_icon = "Js_Bs_03",  worker_min_icon = "Js_Gy_03",  worker_head = "Js_Gy_03",  worker_type = {1001,1002,1003,1004,1005}}
data[1014] = { worker_index = 1014,  worker_name = "小野",  worker_icon = "Js_Bs_04",  worker_min_icon = "Js_Gy_04",  worker_head = "Js_Gy_04",  worker_type = {1001,1002,1003,1004,1005}}
data[1015] = { worker_index = 1015,  worker_name = "金灿灿",  worker_icon = "Js_Bs_06",  worker_min_icon = "Js_Gy_06",  worker_head = "Js_Gy_06",  worker_type = {1001,1002,1003,1004,1005}}
data[1016] = { worker_index = 1016,  worker_name = "丘比",  worker_icon = "Js_Bs_07",  worker_min_icon = "Js_Gy_07",  worker_head = "Js_Gy_07",  worker_type = {1001,1002,1003,1004,1005}}
data[1017] = { worker_index = 1017,  worker_name = "老蓝",  worker_icon = "Js_Bs_08",  worker_min_icon = "Js_Gy_08",  worker_head = "Js_Gy_08",  worker_type = {1001,1002,1003,1004,1005}}
data[1018] = { worker_index = 1018,  worker_name = "小博",  worker_icon = "Js_Bs_09",  worker_min_icon = "Js_Gy_09",  worker_head = "Js_Gy_09",  worker_type = {1001,1002,1003,1004,1005}}
data[1019] = { worker_index = 1019,  worker_name = "黄阿依",  worker_icon = "Js_Bs_10",  worker_min_icon = "Js_Gy_10",  worker_head = "Js_Gy_10",  worker_type = {1001,1002,1003,1004,1005}}
data[1020] = { worker_index = 1020,  worker_name = "艾尼",  worker_icon = "Js_Bs_11",  worker_min_icon = "Js_Gy_11",  worker_head = "Js_Gy_11",  worker_type = {1001,1002,1003,1004,1005}}

return data
