-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { worker_level = 1,  display_level = 1,  worker_exp = 1,  worker_max_exp = 2,  consume_gold = 1,  reduce_time = 1}
data[2] = { worker_level = 2,  display_level = 2,  worker_exp = 2,  worker_max_exp = 4,  consume_gold = 1,  reduce_time = 2}
data[3] = { worker_level = 3,  display_level = 3,  worker_exp = 4,  worker_max_exp = 8,  consume_gold = 2,  reduce_time = 3}
data[4] = { worker_level = 4,  display_level = 4,  worker_exp = 8,  worker_max_exp = 16,  consume_gold = 2,  reduce_time = 4}
data[5] = { worker_level = 5,  display_level = 5,  worker_exp = 16,  worker_max_exp = 32,  consume_gold = 4,  reduce_time = 5}
data[6] = { worker_level = 6,  display_level = 1,  worker_exp = 32,  worker_max_exp = 64,  consume_gold = 4,  reduce_time = 11}
data[7] = { worker_level = 7,  display_level = 2,  worker_exp = 64,  worker_max_exp = 128,  consume_gold = 8,  reduce_time = 12}
data[8] = { worker_level = 8,  display_level = 3,  worker_exp = 128,  worker_max_exp = 256,  consume_gold = 8,  reduce_time = 13}
data[9] = { worker_level = 9,  display_level = 4,  worker_exp = 256,  worker_max_exp = 512,  consume_gold = 16,  reduce_time = 14}
data[10] = { worker_level = 10,  display_level = 5,  worker_exp = 512,  worker_max_exp = 1024,  consume_gold = 16,  reduce_time = 15}
data[11] = { worker_level = 11,  display_level = 1,  worker_exp = 1024,  worker_max_exp = 2048,  consume_gold = 32,  reduce_time = 21}
data[12] = { worker_level = 12,  display_level = 2,  worker_exp = 2048,  worker_max_exp = 4096,  consume_gold = 32,  reduce_time = 22}
data[13] = { worker_level = 13,  display_level = 3,  worker_exp = 4096,  worker_max_exp = 8192,  consume_gold = 64,  reduce_time = 23}
data[14] = { worker_level = 14,  display_level = 4,  worker_exp = 8192,  worker_max_exp = 16384,  consume_gold = 64,  reduce_time = 24}
data[15] = { worker_level = 15,  display_level = 5,  worker_exp = 16384,  worker_max_exp = 32768,  consume_gold = 128,  reduce_time = 25}
data[16] = { worker_level = 16,  display_level = 1,  worker_exp = 32768,  worker_max_exp = 65536,  consume_gold = 128,  reduce_time = 31}
data[17] = { worker_level = 17,  display_level = 2,  worker_exp = 65536,  worker_max_exp = 131072,  consume_gold = 256,  reduce_time = 32}
data[18] = { worker_level = 18,  display_level = 3,  worker_exp = 131072,  worker_max_exp = 262144,  consume_gold = 256,  reduce_time = 33}
data[19] = { worker_level = 19,  display_level = 4,  worker_exp = 262144,  worker_max_exp = 524288,  consume_gold = 512,  reduce_time = 34}
data[20] = { worker_level = 20,  display_level = 5,  worker_exp = 524288,  worker_max_exp = 1048576,  consume_gold = 512,  reduce_time = 35}
data[21] = { worker_level = 21,  display_level = 1,  worker_exp = 1048576,  worker_max_exp = 2097152,  consume_gold = 1024,  reduce_time = 41}
data[22] = { worker_level = 22,  display_level = 2,  worker_exp = 2097152,  worker_max_exp = 4194304,  consume_gold = 1024,  reduce_time = 42}
data[23] = { worker_level = 23,  display_level = 3,  worker_exp = 4194304,  worker_max_exp = 8388608,  consume_gold = 2048,  reduce_time = 43}
data[24] = { worker_level = 24,  display_level = 4,  worker_exp = 8388608,  worker_max_exp = 16777216,  consume_gold = 2048,  reduce_time = 44}
data[25] = { worker_level = 25,  display_level = 5,  worker_exp = 16777216,  worker_max_exp = 16777216,  consume_gold = 4096,  reduce_time = 45}

return data
