-- this file is generated by program!
-- don't change it manaully.


local data = {}

data[1] = { slot_index = 1,  cash = 5}
data[2] = { slot_index = 2,  cash = 5}
data[3] = { slot_index = 3,  cash = 5}
data[4] = { slot_index = 4,  cash = 5}
data[5] = { slot_index = 5,  cash = 5}
data[6] = { slot_index = 6,  cash = 10}
data[7] = { slot_index = 7,  cash = 10}
data[8] = { slot_index = 8,  cash = 10}
data[9] = { slot_index = 9,  cash = 10}
data[10] = { slot_index = 10,  cash = 10}
data[11] = { slot_index = 11,  cash = 15}
data[12] = { slot_index = 12,  cash = 15}
data[13] = { slot_index = 13,  cash = 15}
data[14] = { slot_index = 14,  cash = 15}
data[15] = { slot_index = 15,  cash = 15}
data[16] = { slot_index = 16,  cash = 20}
data[17] = { slot_index = 17,  cash = 20}
data[18] = { slot_index = 18,  cash = 20}
data[19] = { slot_index = 19,  cash = 20}
data[20] = { slot_index = 20,  cash = 20}

return data
